export const serviceCategories = [
  { id: 'catering', label: 'Catering' },
  { id: 'makeup', label: 'Makeup & Beauty' },
  { id: 'photography', label: 'Photography' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'decor', label: 'Decor & Floral' },
  { id: 'security', label: 'Security' },
  { id: 'celebrity', label: 'Celebrity' },
  { id: 'logistics', label: 'Logistics & Support' },
];

export const vendors = [
  { id: 'v1', category: 'catering', name: 'Royal Flavors Catering', image: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80', description: 'Premium multi-cuisine catering for corporate and social events. Serving 50-5000 guests with live counters and buffet setups.', tags: ['North Indian', 'Continental', 'Live Counters', 'Buffet'], rating: 4.5, reviews: 120, location: 'Bhopal, MP', startingPrice: 450, priceUnit: 'Per Plate', services: [{ name: 'Veg Buffet (Basic)', rate: 450, unit: 'Per Plate' }, { name: 'Veg Buffet (Premium)', rate: 650, unit: 'Per Plate' }, { name: 'Non-Veg Buffet', rate: 850, unit: 'Per Plate' }, { name: 'Live Counter Setup', rate: 5000, unit: 'Per Counter' }, { name: 'Welcome Drinks', rate: 50, unit: 'Per Person' }, { name: 'Dessert Station', rate: 100, unit: 'Per Person' }] },
  { id: 'v2', category: 'catering', name: 'Spice Garden Events', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80', description: 'Authentic flavors with modern presentation. Specializing in South Indian and fusion cuisine for weddings and conferences.', tags: ['South Indian', 'Fusion', 'Wedding Catering'], rating: 4.3, reviews: 85, location: 'Bhopal, MP', startingPrice: 350, priceUnit: 'Per Plate', services: [{ name: 'South Indian Thali', rate: 350, unit: 'Per Plate' }, { name: 'Fusion Buffet', rate: 550, unit: 'Per Plate' }, { name: 'Wedding Full Catering', rate: 900, unit: 'Per Plate' }, { name: 'Tea / Coffee Service', rate: 30, unit: 'Per Person' }] },
  { id: 'v3', category: 'makeup', name: 'Glow Studio by Priya', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80', description: 'Award-winning bridal and party makeup artists. HD techniques for every skin tone. On-location services available.', tags: ['Bridal', 'HD Makeup', 'Party', 'On-Location'], rating: 4.8, reviews: 210, location: 'Bhopal, MP', startingPrice: 5000, priceUnit: 'Per Session', services: [{ name: 'Basic Glam Makeup', rate: 5000, unit: 'Per Person' }, { name: 'HD Party Makeup', rate: 8000, unit: 'Per Person' }, { name: 'Bridal Makeup (Full)', rate: 18000, unit: 'Per Person' }, { name: 'Hairstyling', rate: 3000, unit: 'Per Person' }, { name: 'Pre-Bridal Package', rate: 12000, unit: 'Per Session' }] },
  { id: 'v4', category: 'makeup', name: 'Modern Bride Artists', image: 'https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=800&q=80', description: 'Contemporary bridal looks with traditional charm. Expert in corporate grooming and event makeup.', tags: ['Corporate', 'Bridal', 'Event Makeup'], rating: 4.4, reviews: 95, location: 'Indore, MP', startingPrice: 3500, priceUnit: 'Per Session', services: [{ name: 'Corporate Grooming', rate: 3500, unit: 'Per Person' }, { name: 'Event Makeup', rate: 5500, unit: 'Per Person' }, { name: 'Bridal Makeup', rate: 15000, unit: 'Per Person' }, { name: 'Saree/Draping', rate: 2000, unit: 'Per Person' }] },
  { id: 'v5', category: 'photography', name: 'Pixel Perfect Studios', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80', description: 'Cinematic storytelling for weddings and corporate events. Candid photography with drone aerial shots.', tags: ['Candid', 'Drone', 'Cinematic', 'Corporate'], rating: 4.7, reviews: 180, location: 'Bhopal, MP', startingPrice: 15000, priceUnit: 'Per Event', services: [{ name: 'Basic Photo Coverage (4 hrs)', rate: 15000, unit: 'Per Event' }, { name: 'Full Day Photography', rate: 25000, unit: 'Per Day' }, { name: 'Drone Aerial Shoot', rate: 10000, unit: 'Per Session' }, { name: 'Cinematic Video', rate: 20000, unit: 'Per Event' }, { name: 'Photo Album (40 pages)', rate: 8000, unit: 'Per Album' }, { name: 'Same Day Edit (SDE)', rate: 12000, unit: 'Per Event' }] },
  { id: 'v6', category: 'photography', name: 'Cinematic Stories', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80', description: 'Award-winning wedding films and event highlights. Traditional + candid photography packages available.', tags: ['Wedding Films', 'Traditional', 'Candid'], rating: 4.6, reviews: 140, location: 'Bhopal, MP', startingPrice: 20000, priceUnit: 'Per Event', services: [{ name: 'Photography Only', rate: 20000, unit: 'Per Event' }, { name: 'Videography Only', rate: 25000, unit: 'Per Event' }, { name: 'Photo + Video Combo', rate: 40000, unit: 'Per Event' }, { name: 'Highlight Reel (3-5 min)', rate: 8000, unit: 'Per Video' }, { name: 'Pre-Wedding Shoot', rate: 15000, unit: 'Per Session' }] },
  { id: 'v7', category: 'entertainment', name: 'Vibe Entertainment', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80', description: 'Live bands, DJs, and solo performers for all event types. Curated playlists and custom setlists.', tags: ['Live Bands', 'DJs', 'Solo Singers'], rating: 4.5, reviews: 160, location: 'Bhopal, MP', startingPrice: 10000, priceUnit: 'Per Event', services: [{ name: 'DJ Set (4 hrs)', rate: 10000, unit: 'Per Event' }, { name: 'Live Band (3 hrs)', rate: 25000, unit: 'Per Event' }, { name: 'Solo Singer', rate: 15000, unit: 'Per Event' }, { name: 'Sound System Setup', rate: 8000, unit: 'Per Event' }, { name: 'LED Dance Floor', rate: 12000, unit: 'Per Event' }] },
  { id: 'v8', category: 'entertainment', name: 'Indie Artists Hub', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80', description: 'Platform for indie artists, stand-up comedians, and dance troupes. Perfect for corporate events and private functions.', tags: ['Stand-up Comedy', 'Dance Troupes', 'Indie Music'], rating: 4.2, reviews: 72, location: 'Indore, MP', startingPrice: 7000, priceUnit: 'Per Event', services: [{ name: 'Stand-up Comedy (1 hr)', rate: 7000, unit: 'Per Show' }, { name: 'Dance Troupe (6 members)', rate: 18000, unit: 'Per Show' }, { name: 'Indie Band Performance', rate: 12000, unit: 'Per Show' }, { name: 'Flash Mob', rate: 20000, unit: 'Per Event' }] },
  { id: 'v9', category: 'decor', name: 'Decor Dreams', image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80', description: 'Theme-based venue decoration with fresh and artificial floral arrangements. Stage, entrance, and table decor specialists.', tags: ['Stage Decor', 'Floral', 'Theme-Based', 'Table Decor'], rating: 4.6, reviews: 195, location: 'Bhopal, MP', startingPrice: 8000, priceUnit: 'Per Event', services: [{ name: 'Stage Decoration (Basic)', rate: 8000, unit: 'Per Event' }, { name: 'Stage Decoration (Premium)', rate: 18000, unit: 'Per Event' }, { name: 'Entrance Arch', rate: 5000, unit: 'Per Arch' }, { name: 'Table Centerpieces', rate: 800, unit: 'Per Table' }, { name: 'Fresh Floral Arrangements', rate: 3000, unit: 'Per Setup' }, { name: 'Balloon Decor', rate: 4000, unit: 'Per Area' }] },
  { id: 'v10', category: 'security', name: 'Guardian Shield Security', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80', description: 'Licensed security personnel for events of all sizes. Crowd management, VIP detail, and CCTV surveillance setup.', tags: ['Bouncers', 'CCTV', 'VIP Detail', 'Crowd Management'], rating: 4.4, reviews: 88, location: 'Bhopal, MP', startingPrice: 800, priceUnit: 'Per Guard/Day', services: [{ name: 'Security Guard', rate: 800, unit: 'Per Guard/Day' }, { name: 'Bouncer', rate: 1500, unit: 'Per Person/Day' }, { name: 'VIP Security Detail', rate: 5000, unit: 'Per Day' }, { name: 'CCTV Setup (8 cameras)', rate: 8000, unit: 'Per Event' }, { name: 'Crowd Manager', rate: 1200, unit: 'Per Person/Day' }] },
  { id: 'v11', category: 'celebrity', name: 'Star Appearances Agency', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80', description: 'Book Bollywood actors, TV personalities, and social media influencers for your events. Verified bookings with confirmed appearances.', tags: ['Bollywood', 'TV Stars', 'Influencers', 'Brand Ambassadors'], rating: 4.9, reviews: 45, location: 'Pan India', startingPrice: 50000, priceUnit: 'Per Appearance', services: [{ name: 'Meet & Greet (30 min)', rate: 50000, unit: 'Per Appearance' }, { name: 'Stage Performance (1 hr)', rate: 150000, unit: 'Per Event' }, { name: 'Brand Ambassador (1 day)', rate: 250000, unit: 'Per Day' }, { name: 'Social Media Shoutout', rate: 30000, unit: 'Per Post' }, { name: 'Influencer (Micro)', rate: 15000, unit: 'Per Event' }] },
  { id: 'v12', category: 'logistics', name: 'Elite Logistics Solutions', image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80', description: 'End-to-end event logistics — shuttle services, luxury car rentals, professional hosts, and on-site staffing.', tags: ['Shuttle', 'Luxury Cars', 'Hosts', 'Waiters', 'Bartenders'], rating: 4.3, reviews: 110, location: 'Bhopal, MP', startingPrice: 2000, priceUnit: 'Per Service', services: [{ name: 'Shuttle Bus (AC, 32-seater)', rate: 5000, unit: 'Per Trip' }, { name: 'Luxury Car Rental', rate: 3000, unit: 'Per Car/Day' }, { name: 'Host/Hostess', rate: 2000, unit: 'Per Person/Day' }, { name: 'Waiter/Server', rate: 800, unit: 'Per Person/Day' }, { name: 'Bartender', rate: 1500, unit: 'Per Person/Day' }, { name: 'Event Clean-up Crew', rate: 5000, unit: 'Per Event' }] },
];
